services:
  - type: web
    name: rh-backend
    env: node
    region: oregon
    plan: free
    buildCommand: cd backend && npm install --production=false && npx prisma generate && npx prisma migrate deploy && npm run build
    startCommand: cd backend && npm run start:prod
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NPM_CONFIG_PRODUCTION
        value: false
      - key: FRONTEND_URL
        value: https://rh-gppm.onrender.com

  - type: web
    name: rh-gppm
    env: node
    region: oregon
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm run start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://rh-backend.onrender.com
      - key: NEXTAUTH_URL
        value: https://rh-gppm.onrender.com
      - key: NEXTAUTH_SECRET
        generateValue: true
